package(default_visibility = ["//visibility:public"])

filegroup(
    name = "x86_64",
    srcs = glob([
        "x86_64/**",
    ]),
)

filegroup(
    name = "aarch64",
    srcs = glob([
        "aarch64/**",
    ]),
)
