load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "select",
    srcs = ["select.cc"],
    hdrs = ["select.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "stat",
    srcs = ["stat.cc"],
    hdrs = ["stat.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "wait",
    srcs = ["wait.cc"],
    hdrs = ["wait.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "time",
    srcs = ["time.cc"],
    hdrs = ["time.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "ioctl",
    srcs = ["ioctl.cc"],
    hdrs = ["ioctl.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "reboot",
    srcs = ["reboot.cc"],
    hdrs = ["reboot.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "mman",
    srcs = ["mman.cc"],
    hdrs = ["mman.hh"],
    deps = ["//nostdlib:arch"]
)

cc_library(
    name = "mount",
    srcs = ["mount.cc"],
    hdrs = ["mount.hh"],
    deps = ["//nostdlib:arch"]
)